steps:
  # Go to frontend execute build and move dist directory to backend static directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-v', '/workspace:/workspace', '-w', '/workspace/frontend', 'node:16', 'npm', 'run', 'build']
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gleb-abramov/app', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gleb-abramov/app']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'app', '--image', 'gcr.io/gleb-abramov/app', '--region', 'europe-central2', '--allow-unauthenticated', '--project', 'gleb-abramov']
  # Deploy to Firebase
  - name: 'gcr.io/gleb-abramov/firebase'
    args: [ 'deploy', '--project=gleb-abramov' ]
options:
  logging: CLOUD_LOGGING_ONLY