on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build the container image
      - name: 'gcr.io/cloud-builders/docker'
        args: [ 'build', '-t', 'gcr.io/gleb-abramov/app', '.' ]
      # Push the container image to Container Registry
      - name: 'gcr.io/cloud-builders/docker'
        args: [ 'push', 'gcr.io/gleb-abramov/app' ]
      # Deploy container image to Cloud Run
      - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
        entrypoint: gcloud
        args: [ 'run', 'deploy', 'app', '--image', 'gcr.io/gleb-abramov/app', '--region', 'europe-central2', '--allow-unauthenticated', '--project', 'gleb-abramov' ]
      # Deploy to Firebase
      - name: 'gcr.io/gleb-abramov/firebase'
        args: [ 'deploy', '--project=gleb-abramov']