name: Build and Deploy to Firebase Hosting
on:
  push:
    branches: [ "main" ]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: backend/target/app.jar


  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use Google Cloud SDK to authenticate'
        run: |
          gcloud auth login --brief --no-launch-browser --quiet
          gcloud auth configure-docker --quiet

      - name: 'Use  Google Cloud SDK to build and push image to Google Container Registry'
        run: |
          gcloud builds submit --tag gcr.io/gleb-abramov/app --project gleb-abramov

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'app'
          image: 'gcr.io/gleb-abramov/app'
          region: 'europe-central2'
          allow-unauthenticated: 'true'
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - uses: w9jds/setup-firebase@main
        with:
          tools-version: 11.9.0
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase deploy --only hosting
      - run: firebase deploy --only functions
