name: Build and Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: backend/target/app.jar


  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'iam.googleapis.com/projects/51022240282/locations/global/workloadIdentityPools/workload-identity-pool/providers/provider-id-1'
          service_account: 'github-cloudbuild@gleb-abramov.iam.gserviceaccount.com'
          create_credentials_file: true

      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - uses: w9jds/setup-firebase@main
        with:
          tools-version: 11.9.0
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase deploy --only hosting
      - run: firebase deploy --only functions
