name: Build and Deploy to Firebase Hosting
on:
  push:
    branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
        - uses: 'actions/checkout@v3'

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'iam.googleapis.com/projects/510222405282/locations/global/workloadIdentityPools/workload-identity-pool/providers/provider-id-1'
            service_account: 'github-cloudbuild@gleb-abramov.iam.gserviceaccount.com'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'

        - name: Run build script
          run: | 
           chmod +x "${GITHUB_WORKSPACE}/.github/scripts/build.sh"  
           bash "${GITHUB_WORKSPACE}/.github/scripts/build.sh"
           shell: bash
        - id: 'deploy'
          uses: 'google-github-actions/deploy-cloudrun@v1'
          with:
            service: 'app'
            image: 'gcr.io/gleb-abramov/app'
            region: 'europe-central2'
            allow-unauthenticated: 'true'

        - uses: actions/checkout@master
        - uses: actions/setup-node@v3
        - uses: w9jds/setup-firebase@main
          with:
            tools-version: 11.9.0
            firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        - run: firebase deploy --only hosting
        - run: firebase deploy --only functions
