name: Build and Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
        - uses: 'actions/checkout@v3'
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'projects/510222405282/locations/global/workloadIdentityPools/workload-identity-pool/*'
            service_account: 'github-cloudbuild@gleb-abramov.iam.gserviceaccount.com'
        - name: Run build script
          run: | 
           chmod +x "${GITHUB_WORKSPACE}/.github/scripts/build.sh"  
           bash "${GITHUB_WORKSPACE}/.github/scripts/build.sh"
           shell: bash
        - uses: actions/checkout@master
        - uses: actions/setup-node@v3
        - uses: w9jds/setup-firebase@main
          with:
            tools-version: 11.9.0
            firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        - run: firebase deploy --only hosting
        - run: firebase deploy --only functions
